### ISSUE TITLE
Are you using Account Abstraction to create Wallet

### ISSUE THREAD

**Issue by dheeraj-721** [AmbireTech/wallet#10]
Hey guys, I want to know that are you using Account Abstraction for creating wallet or not. If not then how you are creating wallet and perform transaction as signer.

**Comment by Ivshti** [comment]
yes, we are using AA, you can read more in the Ambire Whitepaper: https://ambire.notion.site/ambire/Ambire-Wallet-Whitepaper-d502e54caf584fe7a67f9b0a018cd10f
