### ISSUE TITLE
npm i error that the library 'ambire-common' does not exist

### ISSUE THREAD

**Issue by wf-chen** [AmbireTech/wallet#12]
npm ERR! code 128
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/AmbireTech/ambire-common.git
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

**Comment by Ivshti** [comment]
@wf-chen we made this repo private because of new code there that needs to be audited first, without realizing it would break this repo.

We'll publish the old version to npm so that this repo can be einstalled
