### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by YordanPavlov** [AmbireTech/wallet#7]
Hi there, it seems like the `Readme.md` is not up to date:
```
NOTE: make sure that you use the wallet-v2 branch of the relayer.
```

is this repo still available?

**Comment by Ivshti** [comment]
hey, this repo is meant to be used without the relayer altogether or with the publically available relayer at relayer.ambire.com

**Comment by YordanPavlov** [comment]
Maybe this should be reflected in the documentation? Currently it says:

```
First, clone and run the relayer

git clone https://github.com/AmbireTech/relayer.git -b wallet-v2
cd relayer
npm i
NODE_ENV=development npm start
```

**Comment by Ivshti** [comment]
hey @YordanPavlov, thanks for this, we will update the documentation
